from dataclasses import dataclass
from typing import Optional

@dataclass
class Source:
    """
    Contains frozen information about the origin of the novel data.
    """
    provider_id: str
    provider_name: str
    provider_version: str
    original_url: str
    novel_slug: str # The slug generated by the normalizer
    scraped_at: Optional[str] = None # ISO 8601
    last_updated: Optional[str] = None # From the source, if available

    # TODO: Remove after Phase 2 migration.
    @property
    def providerId(self) -> str:
        return self.provider_id

    # TODO: Remove after Phase 2 migration.
    @property
    def providerName(self) -> str:
        return self.provider_name

    # TODO: Remove after Phase 2 migration.
    @property
    def providerVersion(self) -> str:
        return self.provider_version

    # TODO: Remove after Phase 2 migration.
    @property
    def originalUrl(self) -> str:
        return self.original_url

    # TODO: Remove after Phase 2 migration.
    @property
    def novelSlug(self) -> str:
        return self.novel_slug

    # TODO: Remove after Phase 2 migration.
    @property
    def scrapedAt(self) -> Optional[str]:
        return self.scraped_at

    # TODO: Remove after Phase 2 migration.
    @property
    def lastUpdated(self) -> Optional[str]:
        return self.last_updated
