const CANONICAL_GENRES = new Set([
    "Action",
    "Adventure",
    "Adult",
    "Comedy",
    "Drama",
    "Ecchi",
    "Eastern",
    "Fantasy",
    "Game",
    "Gender Bender",
    "Harem",
    "Historical",
    "History",
    "Horror",
    "Josei",
    "Lolicon",
    "Magical Realism",
    "Martial",
    "Martial Arts",
    "Mature",
    "Mecha",
    "Mystery",
    "Psychological",
    "Psychologic",
    "Reincarnation",
    "Romance",
    "School Life",
    "Sci-fi",
    "Seinen",
    "Shoujo",
    "Shounen",
    "Shounen Ai",
    "Slice of Life",
    "Smut",
    "Sports",
    "Supernatural",
    "Tragedy",
    "Wuxia",
    "Xianxia",
    "Xuanhuan",
    "Yaoi",
    "Yuri",
]);

module.exports = { CANONICAL_GENRES };